server {
    listen 80;
    server_name _;

    add_header X-Content-Type-Options nosniff;
    add_header Cross-Origin-Resource-Policy cross-origin;
    add_header Access-Control-Allow-Origin *;

    location ~* \.(js|map)$ {
        root /usr/share/nginx/html;
        default_type application/javascript;
        add_header Cache-Control "public, max-age=300, immutable" always;
        access_log off;
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
